import Head from "next/head";
// import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <style jsx>
        {`
          h3 {
            font-size: 28px;
          }
        `}
      </style>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Script src="/sc.js" strategy="lazyOnload"></Script> */}

      <main className={styles.main}>
        <h1 className={styles.title}>Hunting Coder</h1>
        {/* when you generate a Static site generation page then you didnot use Image Compoent */}
        {/* <Image className={styles.myImg} src="/sf.jpg" alt="" width={192} height={128} /> */}
        <img className={styles.myImg} src="/sf.jpg" width={192} height={128} alt="" />
        <p className={styles.description}>
          A blog for hunting coders by a hunting coder
        </p>

        <div className="blog">
          <h2>Letest Blogs</h2>
          <div className="blogItem">
            <h3>How to learn JavaScript in 2022?</h3>
            <p>JavaScript is the language used to degign logic for the web</p>
          </div>
          <div className="blogItem">
            <h3>How to learn JavaScript in 2022?</h3>
            <p>JavaScript is the language used to degign logic for the web</p>
          </div>
          <div className="blogItem">
            <h3>How to learn JavaScript in 2022?</h3>
            <p>JavaScript is the language used to degign logic for the web</p>
          </div>
        </div>
      </main>
    </div>
  );
}
